name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cirruslabs/swiftlint-action@v1

  build-and-test-xcode-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: sersoft-gmbh/xcodebuild-action@v4
      with:
        spm-package: './'
        scheme: Animations
        destination: platform=iOS
    - uses: sersoft-gmbh/xcodebuild-action@v4
      with:
        spm-package: './'
        scheme: Animations
        destination: platform=tvOS
        action: test
