name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cirruslabs/swiftlint-action@v1

  build-and-test-iOS-xcode-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get latest simulator
      run: echo "LATEST_SIM_UDID=$(./script/latest-sim)" >> $GITHUB_OUTPUT
      id: latest-sim
    - uses: sersoft-gmbh/xcodebuild-action@v4
      with:
        spm-package: './'
        scheme: Animations
        destination: id=${{ steps.latest-sim.outputs.LATEST_SIM_UDID }}
  